apiVersion: v1
kind: Service
metadata:
  name: saken
  namespace: default
spec:
  selector:
    app: saken
  type: ClusterIP
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: saken
    protocol: TCP
    port: 80
    targetPort: 9099